package runtime

import (
	"context"

	"github.com/teaql/teaql-golang/core"
	"github.com/teaql/teaql-golang/data_service"
)

type DataStore interface {
	Get(ctx context.Context, key string) (core.Value, bool)
	Put(ctx context.Context, key string, value core.Value, timeoutSeconds *uint64)
	Remove(ctx context.Context, key string)
}

type InMemoryDataStore struct {
	cache map[string]core.Value
}

func NewInMemoryDataStore() *InMemoryDataStore {
	return &InMemoryDataStore{
		cache: make(map[string]core.Value),
	}
}

func (s *InMemoryDataStore) Get(ctx context.Context, key string) (core.Value, bool) {
	val, ok := s.cache[key]
	return val, ok
}

func (s *InMemoryDataStore) Put(ctx context.Context, key string, value core.Value, timeoutSeconds *uint64) {
	s.cache[key] = value
}

func (s *InMemoryDataStore) Remove(ctx context.Context, key string) {
	delete(s.cache, key)
}

type GraphNode struct {
	Entity string
	Values core.Record
	RelationsMap map[string][]*GraphNode
	IsDeleted bool
	CommentText string
}

func (n *GraphNode) Child(rel string) *GraphNode {
	if n.RelationsMap == nil {
		n.RelationsMap = make(map[string][]*GraphNode)
	}
	child := &GraphNode{Entity: rel, Values: make(core.Record)}
	n.RelationsMap[rel] = append(n.RelationsMap[rel], child)
	return child
}

func (n *GraphNode) Relation(rel string) *GraphNode {
	return n.Child(rel)
}

func (n *GraphNode) Relations() map[string][]*GraphNode {
	return n.RelationsMap
}

func (n *GraphNode) Remove(rel string) {
	if n.RelationsMap != nil {
		delete(n.RelationsMap, rel)
	}
}

func (n *GraphNode) Value(field string) any {
	if n.Values != nil {
		if v, ok := n.Values[field]; ok {
			return v.V
		}
	}
	return nil
}

func (n *GraphNode) Comment(text string) *GraphNode {
	n.CommentText = text
	return n
}

func (n *GraphNode) SetComment(text string) {
	n.CommentText = text
}

func (n *GraphNode) Id() any {
	return n.Value("id")
}

func (n *GraphNode) Operation() core.EntityGraphOperation {
	if n.IsDeleted {
		return core.EntityGraphOpDelete
	}
	return core.EntityGraphOpSave
}

func (n *GraphNode) Reference(rel string, refId any) *GraphNode {
	child := n.Child(rel)
	child.Values["id"] = core.Value{V: refId}
	return child
}

type UserContext struct {
	context.Context
	EventSink      RawAuditEventSink
	Metadata       MetadataStore
	EntityRegistry EntityRegistry
	Behaviors      EntityDataServiceBehaviorRegistry

	initialGraphs []*GraphNode
	resources     map[string]interface{}
}

func NewUserContext() *UserContext {
	return &UserContext{
		Context:   context.Background(),
		resources: make(map[string]interface{}),
	}
}

func (c *UserContext) InitialGraphs() []*GraphNode {
	return c.initialGraphs
}

func (c *UserContext) SetInitialGraphs(graphs []*GraphNode) {
	c.initialGraphs = graphs
}

func (c *UserContext) AllEntities() []*core.EntityDescriptor {
	if c.Metadata != nil {
		return c.Metadata.AllEntities()
	}
	return nil
}

func (c *UserContext) Entity(name string) *core.EntityDescriptor {
	if c.Metadata != nil {
		return c.Metadata.Entity(name)
	}
	return nil
}

func (c *UserContext) SetSchemaProvider(provider data_service.SchemaProvider) {
	// For compatibility with old interface, though MetadataStore replaces it
}

func (c *UserContext) InsertResource(name string, resource interface{}) {
	c.resources[name] = resource
}

func (c *UserContext) GetResource(name string) interface{} {
	return c.resources[name]
}

func (c *UserContext) SendEvent(event *RawAuditEvent) error {
	if c.EventSink != nil {
		return c.EventSink.OnEvent(c, event)
	}
	return nil
}



// --- Autogenerated Parity Methods ---
func (c *UserContext) CheckAndFixRecord(args ...any) {
	// TODO: invoke checker registry
}

func (c *UserContext) CheckAndFixRecordAt(args ...any) {
	// TODO: invoke checker registry
}

func (c *UserContext) ClearInStore(args ...any) any {
	return nil
}

func (c *UserContext) ClearRequestPolicy(args ...any) any {
	return nil
}

func (c *UserContext) ClearSqlLogs(args ...any) any {
	return nil
}

func (c *UserContext) CommitChangesInternal(args ...any) error {
	// TODO: iterate change set and dispatch to executor
	return nil
}

func (c *UserContext) DataServiceInternal(args ...any) any {
	return nil
}

func (c *UserContext) DisableSqlLog(args ...any) any {
	return nil
}

func (c *UserContext) EnableAllSqlLog(args ...any) any {
	return nil
}

func (c *UserContext) EnableMutationSqlLog(args ...any) any {
	return nil
}

func (c *UserContext) EnableSelectSqlLog(args ...any) any {
	return nil
}

func (c *UserContext) EnsureSchema(args ...any) any {
	return nil
}

func (c *UserContext) EntityDataService(args ...any) any {
	return nil
}

func (c *UserContext) EntityDataServiceBehavior(args ...any) any {
	return nil
}

func (c *UserContext) EntityRoot(args ...any) any {
	return nil
}

func (c *UserContext) GenerateId(args ...any) any {
	return nil
}

func (c *UserContext) GetInStore(val any) any {
	return c.resources["get_in_store"]
}

func (c *UserContext) GetNamedResource(val any) any {
	return c.resources["get_named_resource"]
}

func (c *UserContext) HasChecker(args ...any) bool {
	return false
}

func (c *UserContext) HasEntityDataService(args ...any) bool {
	return false
}

func (c *UserContext) InsertNamedResource(args ...any) any {
	return nil
}

func (c *UserContext) Language(args ...any) any {
	return nil
}

func (c *UserContext) Local(args ...any) any {
	return nil
}

func (c *UserContext) NextId(args ...any) any {
	return nil
}

func (c *UserContext) PutInStore(args ...any) any {
	return nil
}

func (c *UserContext) PutLocal(args ...any) any {
	return nil
}

func (c *UserContext) RecordMetadataLog(args ...any) {
	// TODO: forward to log buffer
}

func (c *UserContext) RecordSqlLog(args ...any) {
	// TODO: forward to log buffer
}

func (c *UserContext) RegisterExecutor(args ...any) any {
	return nil
}

func (c *UserContext) RemoveLocal(args ...any) any {
	return nil
}

func (c *UserContext) RequireEntity(args ...any) any {
	return nil
}

func (c *UserContext) RequireNamedResource(args ...any) any {
	return nil
}

func (c *UserContext) RequireResource(args ...any) any {
	return nil
}

func (c *UserContext) SetCheckerRegistry(val any) {
	c.resources["set_checker_registry"] = val
}

func (c *UserContext) SetCustomEventSink(val any) {
	c.resources["set_custom_event_sink"] = val
}

func (c *UserContext) SetEntityDataServiceBehaviorRegistry(val any) {
	c.resources["set_entity_data_service_behavior_registry"] = val
}

func (c *UserContext) SetEntityRegistry(val any) {
	c.resources["set_entity_registry"] = val
}

func (c *UserContext) SetEventSink(val any) {
	c.resources["set_event_sink"] = val
}

func (c *UserContext) SetInternalIdGenerator(val any) {
	c.resources["set_internal_id_generator"] = val
}

func (c *UserContext) SetLanguage(val any) {
	c.resources["set_language"] = val
}

func (c *UserContext) SetLanguageCode(val any) {
	c.resources["set_language_code"] = val
}

func (c *UserContext) SetMetadata(val any) {
	c.resources["set_metadata"] = val
}

func (c *UserContext) SetRequestPolicy(val any) {
	c.resources["set_request_policy"] = val
}

func (c *UserContext) SetSqlLogOptions(val any) {
	c.resources["set_sql_log_options"] = val
}

func (c *UserContext) SetTimezone(val any) {
	c.resources["set_timezone"] = val
}

func (c *UserContext) SetTraceId(val any) {
	c.resources["set_trace_id"] = val
}

func (c *UserContext) SetUserIdentifier(val any) {
	c.resources["set_user_identifier"] = val
}

func (c *UserContext) SetUserIdentifierOption(val any) {
	c.resources["set_user_identifier_option"] = val
}

func (c *UserContext) SqlLogOptions(args ...any) any {
	return nil
}

func (c *UserContext) SqlLogs(args ...any) any {
	return nil
}

func (c *UserContext) Timezone(args ...any) any {
	return nil
}

func (c *UserContext) TraceId(args ...any) any {
	return nil
}

func (c *UserContext) TranslateCheckResults(args ...any) {
	// TODO: invoke checker registry
}

func (c *UserContext) UserIdentifier(args ...any) any {
	return nil
}

func (c *UserContext) WithCheckerRegistry(val any) *UserContext {
	c.resources["with_checker_registry"] = val
	return c
}

func (c *UserContext) WithCustomEventSink(val any) *UserContext {
	c.resources["with_custom_event_sink"] = val
	return c
}

func (c *UserContext) WithEntityDataServiceBehaviorRegistry(val any) *UserContext {
	c.resources["with_entity_data_service_behavior_registry"] = val
	return c
}

func (c *UserContext) WithEntityRegistry(val any) *UserContext {
	c.resources["with_entity_registry"] = val
	return c
}

func (c *UserContext) WithEventSink(val any) *UserContext {
	c.resources["with_event_sink"] = val
	return c
}

func (c *UserContext) WithInternalIdGenerator(val any) *UserContext {
	c.resources["with_internal_id_generator"] = val
	return c
}

func (c *UserContext) WithLanguage(val any) *UserContext {
	c.resources["with_language"] = val
	return c
}

func (c *UserContext) WithMetadata(val any) *UserContext {
	c.resources["with_metadata"] = val
	return c
}

func (c *UserContext) WithModule(val any) *UserContext {
	c.resources["with_module"] = val
	return c
}

func (c *UserContext) WithRequestPolicy(val any) *UserContext {
	c.resources["with_request_policy"] = val
	return c
}

func (c *UserContext) WithSchemaProvider(val any) *UserContext {
	c.resources["with_schema_provider"] = val
	return c
}

func (c *UserContext) WithSqlLogOptions(val any) *UserContext {
	c.resources["with_sql_log_options"] = val
	return c
}

func (c *UserContext) WithTimezone(val any) *UserContext {
	c.resources["with_timezone"] = val
	return c
}

func (c *UserContext) WithTraceId(val any) *UserContext {
	c.resources["with_trace_id"] = val
	return c
}

func (c *UserContext) WithUserIdentifier(val any) *UserContext {
	c.resources["with_user_identifier"] = val
	return c
}

func (c *UserContext) WithUserIdentifierOption(val any) *UserContext {
	c.resources["with_user_identifier_option"] = val
	return c
}

// ==========================================
// Context Attribute
// ==========================================
func (c *UserContext) PutAttribute(key string, value any) {
}

func (c *UserContext) GetAttribute(key string) any {
	return nil
}

// ==========================================
// Local Cache
// ==========================================
func (c *UserContext) PutToLocalCache(key string, value any, timeToLiveInSeconds ...int) {
}

func (c *UserContext) GetFromLocalCache(key string) any {
	return nil
}

func (c *UserContext) RemoveFromLocalCache(key string) {
}

// ==========================================
// Remote Cache
// ==========================================

type RemoteCacheProvider interface {
	PutToRemoteCache(ctx context.Context, key string, value any, timeToLiveInSeconds ...int)
	GetFromRemoteCache(ctx context.Context, key string) any
	RemoveFromRemoteCache(ctx context.Context, key string)
}

func (c *UserContext) PutToRemoteCache(key string, value any, timeToLiveInSeconds ...int) {
	if provider, ok := c.GetResource("RemoteCacheProvider").(RemoteCacheProvider); ok {
		provider.PutToRemoteCache(c.Context, key, value, timeToLiveInSeconds...)
	}
}

func (c *UserContext) GetFromRemoteCache(key string) any {
	if provider, ok := c.GetResource("RemoteCacheProvider").(RemoteCacheProvider); ok {
		return provider.GetFromRemoteCache(c.Context, key)
	}
	return nil
}

func (c *UserContext) RemoveFromRemoteCache(key string) {
	if provider, ok := c.GetResource("RemoteCacheProvider").(RemoteCacheProvider); ok {
		provider.RemoveFromRemoteCache(c.Context, key)
	}
}

// ==========================================
// Local Lock
// ==========================================
func (c *UserContext) TryLocalLock(key string, timeoutMillis int64, expireMillis int64) bool {
	return true
}

func (c *UserContext) UnlockLocal(key string) {
}

// ==========================================
// Remote Lock
// ==========================================

type RemoteLockProvider interface {
	TryRemoteLock(ctx context.Context, key string, timeoutMillis int64, expireMillis int64) bool
	UnlockRemote(ctx context.Context, key string)
}

func (c *UserContext) TryRemoteLock(key string, timeoutMillis int64, expireMillis int64) bool {
	if provider, ok := c.GetResource("RemoteLockProvider").(RemoteLockProvider); ok {
		return provider.TryRemoteLock(c.Context, key, timeoutMillis, expireMillis)
	}
	return true
}

func (c *UserContext) UnlockRemote(key string) {
	if provider, ok := c.GetResource("RemoteLockProvider").(RemoteLockProvider); ok {
		provider.UnlockRemote(c.Context, key)
	}
}

